inherit_from:
  - '.rubocop_core.yml'

# Put your project-specifc Rubocop config here

Style/IndentationWidth:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/SymbolArray:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/ruby-progressbar.rb'
